{{- range $key, $val := .Values.deployment }} 
{{- if $val.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ $.Release.Name }}-{{$val.name}}-secret"  
spec:
  encryptedData:
    {{- range $sec_key, $sec_val := $val.secrets }}
    {{ $sec_key }}: {{ $sec_val }}
    {{- end }}    
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ $.Release.Name }}-{{$val.name}}-secret
      namespace: {{ $.Release.Namespace }}
---      
{{- end }}
{{- end }}