apiVersion: v2
appVersion: 1.0.0
description: template for deployments in ans , this version supports multiple deployments in one values .yml. , vertical pod autoscaller support
icon: https://www.ant.cl/portal/img/logo_mi_portal.a890b3d2.svg
name: multichart
type: application
version: 0.2.2
