deployment:
  #- nombre de la imagen
  - name: front-example
    image: "paulbouwer/hello-kubernetes"
    # - tag de la imagen
    tag : "1.10"
    # - escalado automatico por defecto verificar uso de deployment para configurar correctamente los request
    requests:
      memory: "250Mi"
      cpu: "100m"
    # -opcional  
    hpa:
      maxReplicas: 3
      minReplicas: 1
    service:
      # - tipo de servicio por defecto ClusterIP ##
      #type: ClusterIP
      # puerto por el cual conectar a  la imagen
      targetPort: 5000  
    ingress:
      #- configuracion de si eliminar o no el path en caso que las apis esten en ruta base /
      strip_path : "true"
      #- path por el cual esta configurada la aplicacion
      path: /example

  - name: backend-example
    image: "paulbouwer/hello-kubernetes"
    # - tag de la imagen
    tag : "1.10"
    # - escalado automatico por defecto verificar uso de deployment para configurar correctamente los request
    requests:
      memory: "250Mi"
      cpu: "100m"
    #opcional  
    hpa:
      maxReplicas: 3
      minReplicas: 1
    vpa: "Off"  
    service:
      # - tipo de servicio por defecto ClusterIP
      #type: ClusterIP
      # puerto por el cual conectar a  la imagen
      targetPort: 4000  
    ingress:
      #- configuracion de si eliminar o no el path en caso que las apis esten en ruta base /
      strip_path : "true"
      # path por el cual esta configurada la aplicacion
      path: /example
  
# - a apartado para los secretos se debe pedir encriptar al equipo de cloud  y son montados automaticamente en variables de entorno

secrets:
  #exampleSecret: exampleValuesecret
# montados automaticamente como variables de entorno, por detras utiliza un configmap en caso de multiples deploy
env: 
  #example: example
       