{{- if .Values.jwt}}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Release.Name }}-jwt
plugin: jwt
disabled: false
config:
  {{- range $key, $val := .Values.jwt.config }}
  {{ $key }}: {{ $val }}
  {{- end }}   
{{- end}}    