{{- if .Values.jwt}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-credential
type: Opaque
stringData:
  kongCredType: jwt
  {{- range $key, $val := $.Values.jwt.credential }}
  {{ $key }}: {{ $val }}
  {{- end }}  
  
{{- end }}