{{- if .Values.apikey}}
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: "{{ .Release.Name }}-apikey-consumer"
  annotations:
    kubernetes.io/ingress.class: kong
username: "{{ .Release.Name }}-apikey-user"
custom_id: "{{ .Release.Name }}-apikey-user"
credentials:
  - {{ .Release.Name }}-apikey-credential
{{- end}}  