apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
spec:
  type : "{{ .Values.service.type }}"
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: "{{ .Release.Name }}"
